PREFIX : <http://ga4gh.org/graph/rdf/ontology#>
SELECT DISTINCT ?variantSet ?name ?position ?sequenceId ?length
FROM <http://ga4gh.org/rdf/{{graph}}>
WHERE {
  ?alleleId a :Allele ;
    rdfs:label "{{allele}}" ;
    :variantSetID ?variantSetId ;
    :name ?name .
  ?variantSetId rdfs:label ?variantSet .
  ?allelePathItemId :alleleID ?alleleId ;
    :length ?length ;
    :start ?position ;
    :pathItemIndex ?index ;
    :sequenceID ?sequenceId1 .
  ?graphJoinId :side1SequenceID ?sequenceId1 ;
    :side2SequenceID ?sequenceId2 ;
    :side1StrandIsForward ?strand .
  FILTER (?sequenceId1 != ?sequenceId2)
  ?sequenceId1 rdfs:label ?sequenceId .
}
ORDER BY ?index
